---
config:
    test_order:     [sortmerna]
    work_dir:  "C:\\Users\\antoi\\Dropbox\\Umea 2017\\Applied Functionnal Genomics\\Assignment\\V2\\testdir"
    reads_dir:     "C:\\Users\\antoi\\Dropbox\\Umea 2017\\Applied Functionnal Genomics\\Assignment\\V2\\testdir"
    clean:     yes
sortmerna:
    database:  "$SORTMERNADB"
    number_of_threads:   2
fastqc:
    zipextract:    yes
    directory:     "raw"