---
config:
    test_order:     [sortmerna]
    work_dir:  "/studenthome/user9/testdata"
    reads_dir:     "/studenthome/user9/testdata"
    clean:     yes
sortmerna:
    database:  "$SORTMERNADB"
    number_of_threads:   2
fastqc:
    zipextract:    yes
    directory:     "raw"